@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiTXVpbDBAeWFob28uY29tIiwibmFtZSI6Ik11cmlsbyIsImlhdCI6MTc1OTk1NDU2NSwiZXhwIjoxNzU5OTgzMzY1fQ.RJCFn5uaIokdNouIJtwbE9_0CzXyrfaocfLC60jpbhM

### Criando as Assinaturas
POST http://localhost:3000/signatures HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "type" : "Free",
    "isActive": true
}

### Criqando Plano de Assinatura
POST http://localhost:3000/signatures/plan HTTP/1.1
Content-Type: application/json


### Ler Todos as Assinaturas
GET http://localhost:3000/signatures HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Ler o type 
GET http://localhost:3000/signatures?type=Basic HTTP/1.1
Content-Type: application/json


    